### ISSUE TITLE
JS+CSS混合方案阻止微信原生下拉出现的顶部

### ISSUE THREAD

**Issue by Gaubee** [Gaubee/blog#100]
下面是我的实现方案：

``` css
    html,body,#body{
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
        border: 0;
        box-sizing: border-box;
    }
    #body{
        overflow-y: scroll;
    }
/*置顶遮罩*/
    #mark{
        position: fixed;
        top: 0;
        left: 0;
        z-index: 10000000;
        width: 0;
        height: 0;
    }
    #mark>.wrap{
        position: fixed;
        width: 100%;
        height: 100%;
        box-sizing: border-box;
        background-color: rgba(0,0,0,0.5);
        pointer-events: none;
    }
```

``` html
<body>
    <div id="mark">
        <div class="wrap"></div>
    </div>
    <div id="body">
    </div>
</body>
```

```js
body.addEventListener("touchstart",function(){
	if(body.scrollTop==0){
		body.scrollTop = 1
	}
});
```

**这种方案有一个弊端，就是网页内容必须足够多来触发滚动。**

一般可以通过强行增加body的高度来触发这个方案。

否则如果网页内容是过少没有滚动条的话，那就转由js进行限制：

``` js
document.addEventListener('touchmove', function stopScrolling(touchEvent) {
    if(body.clientHeight<document.body.clientHeight){
        touchEvent.preventDefault();
    }
}, false);
```

不过js限制的话我还是推荐用这个方案： [yuanzm/preventoverscrolljs](https://github.com/yuanzm/preventoverscrolljs)
