### ISSUE TITLE
MV*框架中使用属性绑定实现事件触发

### ISSUE THREAD

**Issue by Gaubee** [Gaubee/blog#68]
这种方法将可用于绝大多数MV_框架，就像双向绑定的`input-value`的输入会改变所绑定的value值一样。
想象一下，如果你想监听Model中一个值的变动，但这个值发生改变要触发某些函数，相比有些MV_框架会提供给你一个监听功能来监听这些特定的值，但是如果是抽象化的代码呢？比如模板式的代码生成，你并无法获取到这些值，或者是这个值是由多个绑定值合成……

之前 #67 中就有涉及到类似的功能，现在完善出来。

首先定义一个不可见的iframe

``` html
<iframeWrap><iframe src=""></iframe></iframeWrap>
```

``` css
iframeWrap{
    position: absolute;
    height: 0;
    width: 0;
    overflow: hidden;
    top:0;
    left: 0;
}
iframeWrap iframe{
    height: 0;
}
```

而后要把相关的绑定写到width或者height属性上，比如我现在绑定`innerHTML`。那么在MV*框架中`innerHTML`一旦发生改变，iframe的width属性自然也会发生改变，但要注意的是，这时候这个值在计算中将有可能会被当成`NaN`。所以我们要做的就是及时将width值改回到正常数值去（PS：为了避免正常数值和内容相同导致触发不了，我们使用一个随机数），这时候也会触发一次onresize，但只要用缓存对象来判断这次触发是否符合规范即可。
代码如下：

``` js
var _cacheText;
iframeNode.onload = function () {
    iframeNode.contentWindow.onresize = function () {
        if (_cacheText == newText/*新值 === iframeNode.width*/) {
            return
        }
        /*触发相应的函数*/
        loop();
        /*width恢复正常值，确保下次onresize能正常触发*/
        iframeNode.width = ~~(Math.random()*1000);
    }
    iframeNode.contentWindow.onresize();
}
```
